probing:
	g++ -std=c++17 -o probing runner_probing.cpp ProbingHashTable.cpp Hash.cpp

chaining:
	g++ -std=c++17 -o chaining runner_chaining.cpp ChainingHashTable.cpp Hash.cpp

polsleyCoin:
	g++ -std=c++17 -o polsleyCoin polsleyCoin.cpp Hash.cpp

clean:
	rm probing chaining polsleyCoin